# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    # The type of runner that the job will run on
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}
          catch: "npm"

      # Npm Install
      - name: Npm Install
        run: npm install

      # webpack build
      - name: Webpack Build
        run: npx webpack

      # Npm Test
      - name: Npm Test
        run: npm test

      - name: pwd Log
        run: pwd

  cd:
    # The type of runner that the job will run on
    needs: ci
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # cp bundle file
      - name: cp bundle
        run: cp ./public/js/* $HOME/jenkins-tddtest-nodejs/public/js/

      # PM2 reload all
      - name: Pm2 Reload All
        run: $HOME/jenkins-tddtest-nodejs/build.sh
